# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Anytrail' do
  use_frameworks!

  # Pods for Anytrail
  pod 'Alamofire'

  target 'AnytrailTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
